name: Build, Test, and Push to DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: (Optional) run quick tests inline
        run: |
          if [ -f test_hello.py ]; then python test_hello.py; else echo "No tests"; fi

      - name: Build image (tag latest + commit SHA)
        run: |
          IMAGE=robertwrites/hello-app
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run tests
        run: |
          if [ -f test_hello.py ]; then python test_hello.py; else echo "No tests"; fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: robertwrites
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            robertwrites/hello-app:latest
            robertwrites/hello-app:${{ github.sha }}
